name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-core-projects:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build PKHeX.Core
      run: dotnet build PKHeX.Core/PKHeX.Core.csproj --configuration Release --no-restore
    
    - name: Build PKHeX.Drawing
      run: dotnet build PKHeX.Drawing/PKHeX.Drawing.csproj --configuration Release --no-restore
    
    - name: Build PKHeX.Drawing.PokeSprite
      run: dotnet build PKHeX.Drawing.PokeSprite/PKHeX.Drawing.PokeSprite.csproj --configuration Release --no-restore
    
    - name: Build PKHeX.Drawing.Misc
      run: dotnet build PKHeX.Drawing.Misc/PKHeX.Drawing.Misc.csproj --configuration Release --no-restore
    
    - name: Build PKHeX.Drawing.OSX
      run: dotnet build PKHeX.Drawing.OSX/PKHeX.Drawing.OSX.csproj --configuration Release --no-restore

  build-macos-ui:
    runs-on: macos-latest
    needs: build-core-projects
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Install MAUI workload
      run: |
        sudo dotnet workload install maui
    
    - name: Restore dependencies for MAUI
      run: dotnet restore PKHeX.MAUI/PKHeX.MAUI.csproj
    
    - name: Build PKHeX MAUI for macOS
      run: |
        cd PKHeX.MAUI
        dotnet build --configuration Release --no-restore
    
    - name: Verify build output
      run: |
        cd PKHeX.MAUI
        echo "Checking build output..."
        find bin -name "*.app" -type d || echo "No .app bundles found"
        find bin -name "PKHeX.MAUI*" || echo "No PKHeX.MAUI outputs found"
        ls -la bin/Release/ || echo "Release directory not found"
    
    - name: Upload MacOS Build Artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: PKHeX-MacOS-Build
        path: |
          PKHeX.MAUI/bin/Release/
          !PKHeX.MAUI/bin/Release/**/*.pdb
        retention-days: 30